[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npm run build && cd ../frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"